name       : haskell-smallcheck
version    : 1.2.0
release    : 3
source     :
    - https://hackage.haskell.org/package/smallcheck-1.2.0/smallcheck-1.2.0.tar.gz : d6c79227c6138b287ee8113d2cb95b15a6487d3abb7531309629c57b5e80d9f8
license    : BSD-3-Clause
component  : programming.haskell
summary    : SmallCheck is a testing library that allows to verify properties for all test cases up to some depth. The test cases are generated automatically by SmallCheck.
description: |
    SmallCheck is a testing library that allows to verify properties for all test cases up to some depth. The test cases are generated automatically by SmallCheck.
builddeps  :
    - haskell-cabal-install
    - haskell-logict-devel
rundeps    :
    - devel:
        - haskell-logict-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
