name       : haskell-smallcheck
version    : 1.1.4
release    : 2
source     :
    - https://hackage.haskell.org/package/smallcheck-1.1.4/smallcheck-1.1.4.tar.gz : de04b220ca156162b9e7e45f963f71bb26fd1a2e35ec8375651b82ae5d4e5774
license    : BSD-3-Clause
component  : programming.haskell
summary    : SmallCheck is a testing library that allows to verify properties for all test cases up to some depth. The test cases are generated automatically by SmallCheck.
description: "SmallCheck is a testing library that allows to verify properties for all test cases up to some depth. The test cases are generated automatically by SmallCheck. \n"
builddeps  :
    - haskell-cabal-install
    - haskell-logict
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
