name       : haskell-smallcheck
version    : 1.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/smallcheck-1.1.1/smallcheck-1.1.1.tar.gz : 4d17607c1a620491e7e495a17575b73952932c761e7f9bdfa87e0102fb52f9f9
license    : BSD-3-Clause
component  : programming.haskell
summary    : SmallCheck is a testing library that allows to verify properties for all test cases up to some depth. The test cases are generated automatically by SmallCheck. 
description: |
    SmallCheck is a testing library that allows to verify properties for all test cases up to some depth. The test cases are generated automatically by SmallCheck. 
builddeps  :
    - haskell-cabal-install
    - haskell-logict
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
